version: '3.3'

services:
  # ----------------------------------------------------------------
  # AtCoder
  # ----------------------------------------------------------------
  atcoder:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: atcoder_con
    stdin_open: true
    tty: true
    volumes:
      - ./:/app